# enter variables for easy prediction config
city_name = "Melbourne"

# for green roofs, change to "Green"
target_type = "Solar"


# optional settings
img_size = 256
checkpoint_path = "checkpoint"
solar_checkpoint = "Solar_Best.pth"
green_checkpoint = "Green_Best.pth"