# enter variables for easy prediction config
img_dir = "dataset/Melbourne"
checkpoint_name = "Solar_Best.pth"
target_type = "Solar"


# optional settings
img_size = 256
checkpoint_path = "checkpoint"
mask_dir = "predicted_masks"
  